# Generated by Django 2.1.2 on 2018-12-27 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDoList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_content', models.CharField(max_length=264)),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
    ]
